line-height = 1.12

[window]
width = 1784
height = 996
decorations = "Disabled"
opacity = 0.88
opacity-cells = false
blur = false

[fonts]
family = "JetBrains Mono"
size = 16.0

[mars]

[mars.appearance]
preset = "dark"
